### ISSUE TITLE
Artifacts over JPEG image

### ISSUE THREAD

**Issue by tomaka** [PistonDevelopers/image#441] opened 2015-09-16 14:57 UTC
The original:

![Original](http://mdeverdelhan.developpez.com/tutoriel/dynamiclight/tutoriel6/images/normal.jpg)

Here is what image 0.3.12 decodes:

![Bug](http://i.imgur.com/9osWwAR.png)

**Comment by nwin** [comment] 2015-09-16 16:18
Duplicate of #209. I've a working implementation on my computer that fixes this but it still has some bugs with progressive images (currently unsupported).

**Closed by nwin** 2015-09-16 16:18 UTC
