### ISSUE TITLE
Panic in JPEG decoding: shift operation overflowed

### ISSUE THREAD

**Issue by kmcallister** [PistonDevelopers/image#409] opened 2015-05-08 17:12 UTC
[This JPEG](https://github.com/servo/servo/blob/master/tests/ref/test.jpeg) crashes decoding with

```
thread '<main>' panicked at 'shift operation overflowed', src/jpeg/entropy.rs:151
```

**Comment by Xheotris** [comment] 2015-05-08 17:45
I've got the same problem on 0.3.9, and it's turning my images pink when I run with --release. Here's the result of a simple open/resize/save.
![img_5874](https://cloud.githubusercontent.com/assets/9502592/7542105/89f9ed2c-f577-11e4-9489-b1b4dbd18e5d.JPG)

**Comment by nwin** [comment] 2015-05-08 18:09
@kmcallister there are some bugs in the JPEG decoder. It probably won’t be fixed on a short term basis (as it is basically unmaintained atm).  I’m closing this as a duplicate of #209 as this particular image works fine in release build. 

@Xheotris this is a new issue I haven’t seen yet. That only happens with jpeg files? All? Only this?

**Closed by nwin** 2015-05-08 18:09 UTC

**Comment by Xheotris** [comment] 2015-05-08 18:21
@nwin I just did a bit more experimentation and it turns out that it was actually the resize operation. I'll open a new issue.

**Comment by nwin** [comment] 2015-05-12 06:02
This was actually a duplicate of #325 which is now closed. Still, there are some bugs left in the JPEG decoder (#209)
