### ISSUE TITLE
thread '<main>' panicked at 'shift operation overflowed'

### ISSUE THREAD

**Issue by Qard** [PistonDevelopers/image#387] opened 2015-04-17 04:47 UTC
I'm getting a `thread '<main>' panicked at 'shift operation overflowed'` error from [src/jpeg/entropy.rs:151](https://github.com/PistonDevelopers/image/blob/master/src/jpeg/entropy.rs#L151) when I load this image:

![image](https://s-media-cache-ak0.pinimg.com/originals/60/6b/5a/606b5ab9f6beb1e9598e3efdc32509d6.jpg)

It seems like there's something questionable about that code, given the comment. Any ideas?

**Comment by nwin** [comment] 2015-04-19 09:48
Closing as duplicate of #325 (see #209). In the meanwhile you can compile your program in release mode (cargo build/run --release).

**Closed by nwin** 2015-04-19 09:48 UTC
