### ISSUE TITLE
panicked at 'shift operation overflowed', entropy.rs:151

### ISSUE THREAD

**Issue by jarrett** [PistonDevelopers/image#392] opened 2015-04-22 14:22 UTC
I updated to the latest `image`, and now I get this error reading a JPEG:

    thread '<main>' panicked at 'shift operation overflowed', ~/.cargo/git/checkouts/image-f4d4ca6613133df7/master/./src/jpeg/entropy.rs:151

Here's the relevant part of the backtrace:

     1:        0x10b0a87ff - sys::backtrace::write::h652639cd75f0c63cnSs
     2:        0x10b0abb64 - panicking::on_panic::h669c4ea43c1379a9CPw
     3:        0x10b09f015 - rt::unwind::begin_unwind_inner::h3fc7f8f4791b4491lxw
     4:        0x10b09f34c - rt::unwind::begin_unwind_fmt::hb5d695a390fe80eerww
     5:        0x10b0ab43c - rust_begin_unwind
     6:        0x10b0cae55 - panicking::panic_fmt::haa5585921651bddddTC
     7:        0x10b0ca924 - panicking::panic::h7a00000ab5676d24KRC
     8:        0x10b08113a - jpeg::entropy::derive_codes_and_sizes::h7b6c2dba9187b85dZRk
     9:        0x10b0814d6 - jpeg::entropy::derive_tables::h7feb2a86643141c08Vk
    10:        0x10aee73c0 - jpeg::decoder::JPEGDecoder<R>::read_huffman_tables::h7832727739452819256
    11:        0x10aee5b5a - jpeg::decoder::JPEGDecoder<R>::read_metadata::h15411015948459407703
    12:        0x10aee54dd - jpeg::decoder::JPEGDecoder<R>.ImageDecoder::colortype::h2756695996689006199
    13:        0x10aee437b - dynimage::decoder_to_image::h6238989135411857914
    14:        0x10aeb460b - dynimage::load::h6859065701976087660
    15:        0x10aeb2b6e - dynimage::open::h3782749000994800688

**Comment by nwin** [comment] 2015-04-22 14:23
closing as duplicate of #325

**Closed by nwin** 2015-04-22 14:23 UTC

**Comment by jarrett** [comment] 2015-04-23 01:47
@nwin: Are you sure this is a duplicate? #325 doesn't appear to discuss the panic caused by `code <<= diff as usize;`, which is what this bug is about. I'm wondering if there are multiple panics that need to be solved.

Anyway, I've created a tentative patch for this issue, which solves the problem for the JPEGs I'm loading:

(https://github.com/jarrett/image/commit/29201bc5b1c6817e357efde2c78b5812c330fa6b)[https://github.com/jarrett/image/commit/29201bc5b1c6817e357efde2c78b5812c330fa6b]

Admittedly, I haven't reasoned through the question of whether these bit shifts *should* wrap in the first place. I don't feel entirely qualified to make that call as I'm no expert on the JPEG spec. But for now, at least my JPEGs are loading, and the panic is resolved.

**Comment by nwin** [comment] 2015-04-23 05:34
I marked it as a duplicate because it is the same root cause. Can you please file a pull request for your patch?

**Comment by tomaka** [comment] 2015-04-23 05:44
Well, I'd be opposed to adding `#![feature(core)]` in the library.

**Comment by jarrett** [comment] 2015-04-23 13:27
@tomaka: I don't like it either, but is there any way to fix this bug without `#![feature(core)]`? `wrapping_shl` seems to require it.

**Comment by tomaka** [comment] 2015-04-23 14:02
Well, we could replace `wrapping_shl(n)` by either `wrapping_mul(2.pow(n))` or `rotate_left(n)`, but I don't know which behavior is the correct one.

**Comment by jarrett** [comment] 2015-04-23 14:57
I don't know the answer either. What I do know is that `wrapping_shl` works in my admittedly limited testing.

As I see it, the library is currently broken and unusable for a lot of people, and we have a solution which, though imperfect, is thought to work. I'd rather not let the perfect be the enemy of the good. Thus I'd favor using `wrapping_shl` now, rather than leaving the library in a broken state until someone figures out what the absolutely correct solution is.

As a side note, it appears to me that `rotate_left` would produce a different result than `wrapping_shl`. Counterintuitively, `wrapping_shl` doesn't actually seem to wrap around, but rather discards the overflow. (I could be wrong?) Whereas `rotate_left` seems to wrap around. From my limited knowledge, I think `wrapping_mul(2.pow(n))` would give the same result as `wrapping_shl`, although possibly with more CPU cycles.

**Comment by nwin** [comment] 2015-04-23 16:39
`wrapping_mul(2.pow(n))` should work. It’s also quite probable that it gets optimized into a simple shift…

**Comment by jarrett** [comment] 2015-04-23 18:40
Ok. I trust your judgment about the compiler's optimizations, as I don't
know what to expect from it. (I assume this is something LLVM would do, not
rustc itself. Is that right?)

Performance aside, I think your suggestion would always yield the same
result as mine. So I'll go ahead and implement it
