### ISSUE TITLE
imageops::overlay for RGBA images is not quite correct

### ISSUE THREAD

**Issue by andreymal** [PistonDevelopers/image#613] opened 2017-01-20 14:02 UTC
I'm trying to get behavior like in GIMP and I found a problem with the accuracy.

Add white background (RGBA: [255, 255, 255, 255]) for this image using GIMP and subj:
https://i.imgur.com/FzTt9Us.png

If you compare results pixel-to-pixel, you can get this difference:
https://i.imgur.com/XpmsCfP.png

While debugging, I found that result has numbers like `254.99998`, after `f32 => u8` it is `254`. So I can add `0.001` and fix this:

```rust
impl<T: Primitive> Blend for Rgba<T> {
  fn blend(&mut self, other: &Rgba<T>) {
    /* ... */
    // Cast back to our initial type on return
    *self = Rgba([
      NumCast::from((max_t * out_r) + 0.001).unwrap(),
      NumCast::from((max_t * out_g) + 0.001).unwrap(),
      NumCast::from((max_t * out_b) + 0.001).unwrap(),
      NumCast::from((max_t * alpha_final) + 0.001).unwrap()
    ])
  }
}
```

But this is bad solution of course :) But I don't know good solution.

P.S. `round()` is not solution for this image: result is still different.

**Comment by nwin** [comment] 2017-01-20 20:53
Thank you for catching this, `f32::round()` has to be used.

I do not know what causes the different result bit it is not an issue of the accuracy of `f32`. a) because `f32` should be more than enough for that kind of operation and b) because gimp also “only” uses `f32`.

**Comment by andreymal** [comment] 2017-01-20 21:05
GIMP result: https://i.imgur.com/SPVVwmO.png
imageops::overlay result with `f32::round()`: https://i.imgur.com/KwBzdvj.png
Diff: https://i.imgur.com/QB9jBDw.png

So `f32::round()` is very bad for me :(

Or you think GIMP has bug too?

**Comment by nwin** [comment] 2017-01-20 21:15
As I just said: I do not know what causes the different result but it is neither caused by `round` nor by using `f32`.

**Comment by andreymal** [comment] 2017-01-20 22:39
Why do you think that this is not by using `f32`? Something like `0.1 + 0.2 == 0.30000000000000004` — it's enough for errors

**Comment by nwin** [comment] 2017-01-21 07:51
No it’s not. This is the wrong place to discuss how binary numbers work, but please have a look at the number you posted. How long would it take until this error would arrive at a place we would care? Just try out `f64` and you will see that it doesn’t make a difference.

I haven’t counted but the error is about 12 digits away from our issue (which in fact proves that you used `f64` for your example not `f32` for which Rust [will produce 0.3](https://is.gd/NI8MFv)).

**Comment by andreymal** [comment] 2017-01-21 08:24
I think you're wrong

```rust
let mut i: f32 = 0.0;
for _ in 0..10 {
    i = i + (0.1f32 + 0.2f32);
}
println!("{}", i);
```

This code prints `2.9999998` instead of `3.0`, as you can see `f32` accuracy is still low and error can accumulate.

Because `0.1f64 + 0.2f64 == 0.30000000000000004` you should see `f64` accuracy is low too, of course ;)

```rust
let mut i: f64 = 0.0;
for _ in 0..20 {
    i = i + (0.1f64 + 0.2f64);
}
println!("{}", i);
```
Prints `5.999999999999998` instead of `6.0`

If you add 

`println!("{} {} {} {}", max_t * out_r, max_t * out_g, max_t * out_b, max_t * alpha_final);`

in `fn blend`, you can see something like `254.99998` instead of `255.0`, `92.99999` instead of `93.0` or `147.99998` instead of `148.0`, so I still think it is problem with `f32`

If you will use `f64`, you can see  `254.99999999999997` instead of `255.0`, `65.99999999999999` instead of `66.0` or `106.99999999999999` instead of `107.0`, so `f64` accuracy is low too

I hope that these examples will convince you.

**Comment by nwin** [comment] 2017-01-21 10:36
Probably duplicate of #599.

**Closed by nwin** 2017-01-21 10:36 UTC

**Comment by andreymal** [comment] 2017-01-21 10:48
@nwin it will incompatible with GIMP? :'(

**Comment by andreymal** [comment] 2017-01-23 15:59
@nwin I wrote `blend` implementation using `u32` instead of `f32` (range of numbers `0 .. 255` instead of `0.0 .. 1.0`) and this is fully compatible with GIMP too. Just note.

**Comment by andreymal** [comment] 2017-01-23 16:01
Also, this is not duplicate, of course. #599 describes other problem with blending.
